# Generated by Django 5.2.13 on 2026-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='privacy_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_date',
            field=models.DateTimeField(),
        ),
    ]
