# Generated by Django 5.2.13 on 2026-06-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_legal_privacy_date_alter_legal_terms_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Operador'), ('MIEMBRO', 'Miembro'), ('MIEMBRO_ITINERANTE', 'Miembro Itinerante'), ('VISITANTE', 'Visitante')], max_length=50, unique=True),
        ),
    ]
