# Generated by Django 5.2.13 on 2026-06-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='resource_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='benefits', to='users.resource_type'),
            preserve_default=False,
        ),
    ]
