# Generated by Django 5.2.13 on 2026-05-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_benefit_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad incluida. Null = ilimitado.', null=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benefits', to='users.resource_type'),
        ),
        migrations.AlterField(
            model_name='membership_type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
