# Generated by Django 5.2.13 on 2026-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_benefit_description_benefit_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_type',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='membership_type',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
