# Generated by Django 5.2.13 on 2026-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_membership_type_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
