# Generated by Django 5.2.13 on 2026-06-18 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_benefit_is_active_alter_benefit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Operador'), ('MIEMBRO', 'Miembro'), ('MIEMBRO_ITINERANTE', 'Miembro Itinerante'), ('VISITANTE', 'Visitante')], default='MIEMBRO', max_length=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefit',
            name='description',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='privacy_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_resources', to='users.resource'),
        ),
        migrations.AlterField(
            model_name='membership_type',
            name='description',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membership_type',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='resource_type',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
