# Generated by Django 5.2.13 on 2026-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_membership_type_monthly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Operador'), ('MIEMBRO', 'Miembro'), ('MIEMBRO_ITINERANTE', 'Miembro Itinerante'), ('VISITANTE', 'Visitante')], default='MIEMBRO_ITINERANTE', max_length=50),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
