# Generated by Django 5.2.13 on 2026-06-23 15:30

import django.db.models.manager
import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_benefit_created_at_benefit_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='membership_type',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='resource_type',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='benefit',
            managers=[
                ('objects', users.managers.SoftDeleteManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.managers.SoftDeleteUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='membership_type',
            managers=[
                ('objects', users.managers.SoftDeleteManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resource',
            managers=[
                ('objects', users.managers.SoftDeleteManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resource_type',
            managers=[
                ('objects', users.managers.SoftDeleteManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='membership_type',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='resource_type',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AddConstraint(
            model_name='benefit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_benefit_name'),
        ),
        migrations.AddConstraint(
            model_name='membership_type',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_membership_type_name'),
        ),
        migrations.AddConstraint(
            model_name='resource_type',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_resource_type_name'),
        ),
    ]
