# Generated by Django 5.2.13 on 2026-06-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_payment_invoice_alter_benefit_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_bookable',
            field=models.BooleanField(default=True),
        ),
    ]
