services:
  db:
    image: postgres:17
    container_name: workhood
    restart: always
    environment:
      POSTGRES_USER: workhood
      POSTGRES_PASSWORD: workhood
      POSTGRES_DB: workhood
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: