# Generated by Django 5.2.13 on 2026-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_active_payment_method_code',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='code',
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_payment_method_name'),
        ),
    ]
