# Generated by Django 5.2.13 on 2026-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_payments', '0002_remove_paymentmethod_unique_active_payment_method_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='member_visible',
            field=models.BooleanField(default=True),
        ),
    ]
