# Generated by Django 5.2.13 on 2026-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_payments', '0003_paymentmethod_member_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
