# Generated by Django 5.2.13 on 2026-06-20 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_customuser_role_delete_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reservation_type', models.CharField(choices=[('HOURLY', 'Por horas'), ('DAILY', 'Día completo'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='HOURLY', max_length=20)),
                ('state', models.CharField(choices=[('Pending', 'Pendiente'), ('Confirmed', 'Confirmada'), ('Cancelled', 'Cancelada')], default='Pending', max_length=20)),
                ('recurrence_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='users.membership')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='users.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
