# Generated by Django 5.2.13 on 2026-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceschedule',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spaceschedule',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
