# Generated by Django 5.2.13 on 2026-06-23 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_payments', '0001_initial'),
        ('reservations', '0003_alter_spaceschedule_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='invoices_payments.invoice'),
        ),
    ]
