# Generated by Django 5.2.13 on 2026-06-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_resource_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('result', models.CharField(choices=[('PERMITIDO', 'Permitido'), ('DENEGADO', 'Denegado')], max_length=10)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_nif_cif', models.CharField(blank=True, max_length=20, null=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to='users.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
